print("Welcome, to the millions watching at home ")
print("")
print("")
print("")
print("We are just a few 15 secounds away from the launch")
print("")
print("")
print("")
print("")
print("")
print("10")
print("9")
print("8")
print("7")
print("6")
print("5")
print("4")
print("3")
print("2")
print("1")
print("Blast Off")